# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20170526_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends',
            old_name='friend_id',
            new_name='friend',
        ),
        migrations.RenameField(
            model_name='friends',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='friends',
            unique_together=set([('user', 'friend')]),
        ),
    ]
