# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20170527_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends_status',
            name='id',
        ),
        migrations.AlterField(
            model_name='friends',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Friends_Status'),
        ),
        migrations.AlterField(
            model_name='friends_status',
            name='code',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, unique=True),
        ),
    ]
