# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20170528_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends',
            old_name='user',
            new_name='user1',
        ),
        migrations.RenameField(
            model_name='friends',
            old_name='friend',
            new_name='user2',
        ),
        migrations.AlterUniqueTogether(
            name='friends',
            unique_together=set([('user1', 'user2')]),
        ),
    ]
