# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 12:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20170528_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friends',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
