# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20170529_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='img',
        ),
        migrations.AddField(
            model_name='user',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=user.models.User.user_thumbnail_path),
        ),
    ]
